env:
  global:
    secure: MV2eipopJgKa0gCfkfeGGmBDdivPAZeWkdS/J6XP4tbJ1GY4QgvwZDosvfq8dV84bb/2VAa6JV+nBR88GIaq34MxSfN3lR2oYfT73E/+IWsAM/AwrWGBRFF7SoA+INUnsggausUlhGehP/MlGQRG9p6vD5Te1wN7rj9cHZzKY63NCcYu93UZhRfqHJBZYq+joBWUPeGDaxkThE4E2jf4FEmRMU5vPkwyFDaQfXFj6MbNxkWPgOe3YERYemOPWXTC/WzQNyLmJxYfSPU3uI2WlheEYRHTr7Vui2kxKDvA0bymbXjmm4nkM2jWdrcaUytBW/br8QsNgUwPPI1lSpuQqVNqs5DMV06So+0scYjWcrWjtK2VFqHl7C8oNlLLr5ZWQ2YQ657yPg4z9qcsO9EB027VDMqZteDYoILdHyDAW+X+JsDllw1hm4eXYiREQUyQqzsk0CtyJB8uYBE3VZ0mKVNEgC4nhmWEqCcw/YXqDW6N/7g2IbtGgQqLQ6u9MsGUX+MvMQjCcOvvmM3NVxsPQtWRYISTXWCvIxmhlnz6pSQiQ+XIbd/Xqw5IXjXFxtuTGNkM9TDXWQMt/xGzeyko7Lxz2NRvBFGqYSw9sJ4a2oTW3DgstGNmt5OPCpr0TSDgGiJCYgZ6M1VFR+n6Vl1XCbaFH1+p7x67C73qiCo9vZ8=

language: node_js
node_js: "stable"

before_install:
  - npm i hexo-cli -g

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  skip_cleanup: true
  local_dir: public
  on:
    repo: kezhenxu94/kezhenxu94.github.io
    branch: master

cache:
  directories:
    - node_modules
