env:
  global:
    secure: T9mBx3cDceDsm5G5zFOk2jVoxfO5vDndjiMiLgg977dZUGNm8ma1nGWxqnD3dQltgwqQmxNgCMUGNEtfigPokRrnjgeMMuqnu5uiFtczY9bj43hCtia18Dg95EYvNEZjA83TEMfaG0VxxjRPXP3klDgFDOLCXzsvHPGK1iKcoYhhT+5FBiVjeVtrqCDDqXv7rjXl4gHZi7kKq/k9cKNe7+RuiQyhsWXu36DKY7MWYHKfbRdf2OfSMlOLf8Z87wMgfJL0ZQECRQXjjqutWR7Q6i1SHgCP++IyQOhEegUOqmh+KWxZMEIjVaVXhTSfj3P4ukGMuOZmS4dCrftDOlY+GYO6Kh7aweVKm6d2bGVXhh6LXQWu32TBB5LW6uBCxVJ6G0JirEXrwY+IQruiuXzS76g4DLqArnyv8dId9yXg9dy9e+/ZYvrZPP01tdJ/jBvUzFF5NPX6wHLDCAX1goXFFQSmqijLWHAiMr8ZDm96I8vHnG3Su6NwUiJibM3Xus1XpWCRxpP9yHksokwZKyLWA0p1rAg9lE4h8B2MUv5v4u43Oz26cp/OGvfzLiN38JMgwpgP+APwwDHkSp2GaO2k3dI7xn91V6K8a/VrQRA93HjZ5z6/ahneq6vn2QaLLAucp4W3QlXIXMJdw0L5wrCM9z0nzj3cjVqAhSpYBfI/2Yg=

language: node_js
node_js: "stable"

before_install:
  - npm i hexo-cli -g

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  skip_cleanup: true
  local_dir: public
  on:
    repo: kezhenxu94/kezhenxu94.github.io
    branch: master

cache:
  directories:
    - node_modules
