language: node_js
node_js: stable

before_install:
  - npm i hexo-cli -g

script:
  - hexo clean
  - hexo generate

deploy:
  provider: pages
  github-token: "$GITHUB_TOKEN"
  skip_cleanup: true
  local_dir: public
  target-branch: master
  on:
    repo: kezhenxu94/kezhenxu94.github.io
    branch: src

notifications:
  email:
    on_success: always
    on_failure: always
