title: Kids the Programmer
subtitle: Zhenxu Ke
description: >-
    Zhenxu Ke is currently employed by [@Alibaba](https://github.com/alibaba), where he is part of the CI/CD team.
    During his spare time, he enjoys contributing to open-sourced projects, now he is a member of the [Apache SkyWalking](https://github.com/apache/skywalking) PMC (Project Management Committee), and is a committer of the [Apache Dubbo](https://github.com/apache/dubbo) project.
author: kezhenxu94
language: en
timezone: Asia/Shanghai

url: http://kezhenxu94.github.io
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

new_post_name: :title.md
default_layout: post
titlecase: false
external_link: true
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: false
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: '    '
  
index_generator:
  path: ''
  per_page: 0
  order_by: -date
  
default_category: uncategorized
category_map:
tag_map:

date_format: YYYY-MM-DD
time_format: HH:mm:ss

per_page: 0
pagination_dir: page

theme: cactus

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '

deploy:
  type: git
  repo: git@github.com:kezhenxu94/kezhenxu94.github.io.git
  branch: master

