apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Release.Name }}-gateway
spec:
  selector:
    {{- range $key, $value :=  .Values.gateway.selector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      tls:
        httpsRedirect: false
      hosts:
      {{ .Values.gateway.http.hosts | toYaml | nindent 6 }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ .Release.Namespace }}-{{ .Release.Name }}
        maxProtocolVersion: TLSV1_2
      hosts:
      {{ .Values.gateway.https.hosts | toYaml | nindent 6 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-ingress
spec:
  hosts:
  {{ .Values.gateway.http.hosts | toYaml | nindent 2 }}
  gateways:
    - {{ .Release.Name }}-gateway
  http:
    - route:
        - destination:
            port:
              number: 80
            host: {{ .Release.Name }}
