apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}
  namespace: istio-system
spec:
  acme:
    email: {{ .Values.gateway.issuer.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: {{ .Release.Namespace }}-{{ .Release.Name }}
    solvers:
      - http01:
          ingress:
            class: istio
            ingressTemplate:
              metadata:
                labels:
                  app: istio
